name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build --if-present

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webpack artifacts
        path: public/
  
  test:
    runs-on: ubuntu-latest
    # add the build job as a dependency
    needs: build

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Dowload artifacts
      uses: actions/download-artifact@v2
      with:
        # must match the name given for upload-artifact action in build job
        name: webpack artifacts
        path: public

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test
      run: |
        npm ci
        npm run update-snapshot
        npm run test
      env:
        CI: true